services:
  postgres:
    container_name: ${APP_NAME}-postgres
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ../schema:/docker-entrypoint-initdb.d
    environment:
      TZ: UTC
      LANG: ja_JP.UTF-8
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_HOST_AUTH_METHOD: trust
    command: ["postgres", "-c", "log_statement=all"]
    restart: always
  redis:
    container_name: ${APP_NAME}-redis
    image: redis:7-alpine
    ports:
      - 6379:6379
    restart: always
  api:
    container_name: ${APP_NAME}-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - workdir=.docker
    ports:
      - 8080:8080
    environment:
      ENV: local
      PORT: 8080
      POSTGRES_URL: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      KV_URL: redis:6379
    volumes:
      - ../:/app
    depends_on:
      - postgres
      - redis
    restart: always
